version: '3.9'

services:
  labuona_app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/labuona 

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: labuona
    volumes:
      - data:/var/lib/postgresql/data