version: '3.9'

services:
  labuona_app:
    container_name: labuona-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/home/node/app
# depends_on:
#   - users_api_dev
