version: '3.9'

services:
  labuona_app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: labuonapasta
      MYSQL_ROOT_PASSWORD: teste123
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    restart: always